apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-mitsuha
spec:
  displayName: mitsuha.
  author:
    name: Halo
    website: "https://github.com/halo-dev"
  description: mitsuha theme for halo, by honami#597. 
  logo: "https://mitsuha.ren/favicon"
  homepage: "https://mitsuha.ren/blog/theme-mitsuha"
  repo: "https://github.com/leewp14/halo-theme-mitsuha"
  issues: "https://github.com/leewp14/halo-theme-mitsuha/issues"
  settingName: "theme-mitsuha-setting"
  configMapName: "theme-mitsuha-configMap"
  version: "h0-1"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
